Repository Project-MO-A/Backend, pull requests merged in 2023-04, with the labels that each got.

#59 test: 테스트 코드 리팩토링 및 추가 작성
  src/main/java/com/moa/controller/AttendMemberController.java
  src/main/java/com/moa/controller/NoticeController.java
  src/main/java/com/moa/controller/RecruitMemberController.java
  src/main/java/com/moa/controller/RecruitmentController.java
  src/main/java/com/moa/controller/UserController.java
  src/main/java/com/moa/domain/member/AttendMemberRepository.java
  src/main/java/com/moa/domain/member/RecruitMemberRepository.java
  src/main/java/com/moa/domain/user/User.java
  src/main/java/com/moa/dto/BooleanResponse.java
  src/main/java/com/moa/dto/ValueResponse.java
  src/main/java/com/moa/dto/notice/PostNoticeRequest.java
  src/main/java/com/moa/dto/user/UserUpdateRequest.java
  src/main/java/com/moa/global/auth/model/Claims.java
  src/main/java/com/moa/global/auth/model/TokenMapping.java
  src/main/java/com/moa/global/auth/token/AccessTokenProvider.java
  src/main/java/com/moa/global/auth/token/JwtProvider.java
  src/main/java/com/moa/global/auth/token/RefreshTokenProvider.java
  src/main/java/com/moa/global/auth/token/TokenExtractor.java
  src/main/java/com/moa/global/auth/token/TokenInjector.java
  src/main/java/com/moa/global/auth/utils/AuthorityToStringConvertor.java
  src/main/java/com/moa/global/auth/utils/JwtService.java
  src/main/java/com/moa/global/config/WebBeanConfig.java
  src/main/java/com/moa/global/config/sub/SecurityFilterBeanConfig.java
  src/main/java/com/moa/global/exception/ErrorCode.java
  src/main/java/com/moa/global/filter/JwtAuthenticationFilter.java
  src/main/java/com/moa/global/filter/LoginProcessFilter.java
  src/main/java/com/moa/global/filter/handler/JwtProviderHandler.java
  src/main/java/com/moa/service/AttendMemberService.java
  src/main/java/com/moa/service/RecruitMemberService.java
  src/main/resources/application.yml
  src/main/resources/messages.properties
  src/test/java/com/moa/base/AbstractControllerUnitTest.java
  src/test/java/com/moa/base/AbstractServiceTest.java
  src/test/java/com/moa/controller/AttendMemberControllerUnitTest.java
  src/test/java/com/moa/controller/NoticeControllerUnitTest.java
  src/test/java/com/moa/controller/RecruitMemberControllerUnitTest.java
  src/test/java/com/moa/controller/UserControllerUnitTest.java
  src/test/java/com/moa/domain/member/AdminRepositoryTest.java
  src/test/java/com/moa/domain/member/AttendMemberRepositoryTest.java
  src/test/java/com/moa/domain/member/RecruitMemberRepositoryTest.java
  src/test/java/com/moa/domain/notice/NoticeRepositoryTest.java
  src/test/java/com/moa/domain/user/UserRepositoryTest.java
  src/test/java/com/moa/global/auth/token/AbstractJwtProvider.java
  src/test/java/com/moa/global/auth/token/AccessTokenProviderTest.java
  src/test/java/com/moa/global/auth/token/JwtProviderTest.java
  src/test/java/com/moa/global/auth/utils/JwtServiceTest.java
  src/test/java/com/moa/global/filter/JwtAuthenticationFilterTest.java
  src/test/java/com/moa/global/filter/LoginProcessFilterUnitTest.java
  src/test/java/com/moa/global/filter/constant/FilterConstant.java
  src/test/java/com/moa/service/PossibleTimeServiceTest.java
  src/test/java/com/moa/service/RecruitMemberServiceTest.java
  src/test/java/com/moa/service/unit/NoticeServiceUnitTest.java
  src/test/java/com/moa/service/unit/RecruitMemberServiceUnitTest.java
  src/test/java/com/moa/service/unit/UserServiceUnitTest.java
Labels: Test, Refactoring

#58 test: 테스트 격리를 위한 테스트 코드 리팩토링
  src/main/java/com/moa/InitData.java
  src/main/java/com/moa/controller/AdminController.java
  src/main/java/com/moa/controller/PossibleTimeController.java
  src/main/java/com/moa/controller/RecruitmentController.java
  src/main/java/com/moa/domain/member/ApplimentMember.java
  src/main/java/com/moa/domain/member/RecruitMemberRepository.java
  src/main/java/com/moa/domain/recruit/Recruitment.java
  src/main/java/com/moa/domain/recruit/tag/TagRepository.java
  src/main/java/com/moa/dto/member/RecruitMemberRequest.java
  src/main/java/com/moa/dto/possible/PossibleTimeData.java
  src/main/java/com/moa/dto/possible/PossibleTimeResponse.java
  src/main/java/com/moa/dto/recruit/RecruitPostRequest.java
  src/main/java/com/moa/dto/recruit/RecruitUpdateRequest.java
  src/main/java/com/moa/global/exception/ErrorCode.java
  src/main/java/com/moa/global/exception/GlobalControllerAdvice.java
  src/main/java/com/moa/global/exception/service/InvalidRequestException.java
  src/main/java/com/moa/service/AdminService.java
  src/main/java/com/moa/service/PossibleTimeService.java
  src/main/java/com/moa/service/RecruitMemberService.java
  src/main/java/com/moa/service/RecruitmentService.java
  src/main/java/com/moa/service/TagService.java
  src/main/resources/application.yml
  src/main/resources/messages.properties
  src/test/java/com/moa/InitData.java
  src/test/java/com/moa/base/RepositoryTest.java
  src/test/java/com/moa/base/RepositoryTestCustom.java
  src/test/java/com/moa/controller/AdminControllerTest.java
  src/test/java/com/moa/controller/PossibleTimeControllerTest.java
  src/test/java/com/moa/controller/RecruitmentControllerTest.java
  src/test/java/com/moa/domain/member/AdminRepositoryTest.java
  src/test/java/com/moa/domain/member/ApplimentMemberRepositoryTest.java
  src/test/java/com/moa/domain/possible/PossibleTimeRepositoryTest.java
  src/test/java/com/moa/domain/recruit/RecruitmentRepositoryTest.java
  src/test/java/com/moa/domain/recruit/tag/TagRepositoryTest.java
  src/test/java/com/moa/service/AdminServiceTest.java
  src/test/java/com/moa/service/AlarmServiceTest.java
  src/test/java/com/moa/service/AlarmServiceUnitTest.java
  src/test/java/com/moa/service/NoticeServiceTest.java
  src/test/java/com/moa/service/PossibleTimeServiceTest.java
  src/test/java/com/moa/service/RecruitmentServiceTest.java
  src/test/java/com/moa/service/TagServiceTest.java
  src/test/java/com/moa/support/config/TestQueryDslConfig.java
  src/test/java/com/moa/support/fixture/ApplimentFixture.java
  src/test/java/com/moa/support/fixture/AttendMemberFixture.java
  src/test/java/com/moa/support/fixture/NoticeFixture.java
  src/test/java/com/moa/support/fixture/PossibleTimeFixture.java
  src/test/java/com/moa/support/fixture/RecruitMemberFixture.java
  src/test/java/com/moa/support/fixture/RecruitRequestFixture.java
  src/test/java/com/moa/support/fixture/RecruitmentFixture.java
  src/test/java/com/moa/support/fixture/TagFixture.java
  src/test/java/com/moa/support/fixture/UserFixture.java
Labels: Test, Refactoring

#63 refactor: 모집 멤버 수정 로직 변경
  src/main/java/com/moa/InitData.java
  src/main/java/com/moa/domain/member/ApplimentMember.java
  src/main/java/com/moa/domain/member/RecruitMember.java
  src/main/java/com/moa/domain/member/RecruitMemberRepository.java
  src/main/java/com/moa/domain/recruit/Recruitment.java
  src/main/java/com/moa/domain/recruit/RecruitmentRepository.java
  src/main/java/com/moa/dto/member/RecruitMemberRequest.java
  src/main/java/com/moa/dto/member/RecruitMemberResponse.java
  src/main/java/com/moa/dto/recruit/RecruitInfoResponse.java
  src/main/java/com/moa/global/exception/ErrorCode.java
  src/main/java/com/moa/global/exception/service/MemberStatusException.java
  src/main/java/com/moa/service/RecruitmentService.java
  src/main/resources/messages.properties
  src/test/java/com/moa/domain/member/RecruitMemberRepositoryTest.java
  src/test/java/com/moa/service/NoticeServiceTest.java
  src/test/java/com/moa/service/RecruitmentServiceTest.java
  src/test/java/com/moa/support/fixture/RecruitRequestFixture.java
Labels: fix, Refactoring

#68 refactor: state 반환 값 변경
  src/main/java/com/moa/dto/recruit/RecruitInfoResponse.java
Labels: Refactoring

#70 기타 수정사항
  build.gradle
  src/main/java/com/moa/controller/NoticeController.java
  src/main/java/com/moa/domain/member/AttendMember.java
  src/main/java/com/moa/domain/notice/Notice.java
  src/main/java/com/moa/domain/notice/NoticeRepository.java
  src/main/java/com/moa/domain/recruit/RecruitStatus.java
  src/main/java/com/moa/domain/recruit/Recruitment.java
  src/main/java/com/moa/dto/notice/Kakao.java
  src/main/java/com/moa/dto/notice/NoticesResponse.java
  src/main/java/com/moa/dto/notice/PostNoticeRequest.java
  src/main/java/com/moa/dto/notice/UpdateNoticeRequest.java
  src/main/java/com/moa/dto/recruit/RecruitmentInfo.java
  src/main/java/com/moa/dto/recruit/RecruitmentsInfo.java
  src/main/java/com/moa/dto/user/UserActivityInfo.java
  src/main/java/com/moa/dto/user/UserInfo.java
  src/main/java/com/moa/dto/user/UserRecruitmentInterestInfo.java
  src/main/java/com/moa/global/config/SecurityConfig.java
  src/main/java/com/moa/global/exception/ErrorCode.java
  src/main/java/com/moa/global/exception/service/VoteFinishException.java
  src/main/java/com/moa/service/AttendMemberService.java
  src/main/java/com/moa/service/NoticeService.java
  src/main/java/com/moa/service/util/GrahamUtils.java
  src/main/java/com/moa/service/util/KakaoUtils.java
  src/main/resources/application.yml
  src/test/java/com/moa/controller/NoticeControllerUnitTest.java
  src/test/java/com/moa/controller/RecruitmentControllerTest.java
  src/test/java/com/moa/domain/notice/NoticeRepositoryTest.java
  src/test/java/com/moa/service/NoticeServiceTest.java
  src/test/java/com/moa/service/unit/NoticeServiceUnitTest.java
  src/test/java/com/moa/service/unit/UserServiceUnitTest.java
Labels: feat

#72 refactor: 모집글 조회 관련 필드 변경
  src/main/java/com/moa/domain/recruit/RecruitmentRepository.java
  src/main/java/com/moa/domain/user/UserRepository.java
  src/main/java/com/moa/dto/recruit/RecruitInfoResponse.java
  src/main/java/com/moa/dto/recruit/RecruitmentInfo.java
  src/main/java/com/moa/dto/recruit/RecruitmentInterestInfo.java
  src/main/java/com/moa/dto/recruit/RecruitmentsInfo.java
  src/main/java/com/moa/dto/user/UserRecruitmentInterestInfo.java
  src/main/java/com/moa/global/filter/handler/RecruitmentAuthorizationManagerForAuthor.java
  src/main/java/com/moa/service/RecruitmentService.java
  src/main/java/com/moa/service/UserService.java
  src/test/java/com/moa/domain/recruit/RecruitmentRepositoryTest.java
  src/test/java/com/moa/service/RecruitmentServiceTest.java
  src/test/java/com/moa/service/unit/UserServiceUnitTest.java
Labels: Refactoring

#75 feat: Reply Entity 매핑
  src/main/java/com/moa/domain/reply/Reply.java
Labels: Entity

#76 feat: 댓글 등록 조회기능
  src/main/java/com/moa/controller/RecruitmentController.java
  src/main/java/com/moa/controller/ReplyController.java
  src/main/java/com/moa/domain/reply/ReplyRepository.java
  src/main/java/com/moa/dto/recruit/RecruitInfoReplyResponse.java
  src/main/java/com/moa/dto/reply/RepliesInfo.java
  src/main/java/com/moa/dto/reply/ReplyPostRequest.java
  src/main/java/com/moa/global/exception/ErrorCode.java
  src/main/java/com/moa/service/ReplyService.java
  src/main/resources/messages.properties
  src/test/java/com/moa/base/AbstractServiceTest.java
  src/test/java/com/moa/controller/RecruitmentControllerTest.java
  src/test/java/com/moa/domain/reply/ReplyRepositoryTest.java
  src/test/java/com/moa/service/ReplyServiceTest.java
Labels: feat

#80 feat: 댓글 수정, 삭제 기능 추가
  src/main/java/com/moa/controller/ReplyController.java
  src/main/java/com/moa/domain/reply/Reply.java
  src/main/java/com/moa/domain/reply/ReplyRepository.java
  src/main/java/com/moa/dto/recruit/RecruitmentInfo.java
  src/main/java/com/moa/dto/reply/ReplyUpdateRequest.java
  src/main/java/com/moa/global/exception/ErrorCode.java
  src/main/java/com/moa/global/exception/service/ReplyAuthorityException.java
  src/main/java/com/moa/service/RecruitmentSearchService.java
  src/main/java/com/moa/service/ReplyService.java
  src/main/resources/messages.properties
  src/test/java/com/moa/domain/reply/ReplyRepositoryTest.java
  src/test/java/com/moa/service/RecruitmentSearchServiceTest.java
  src/test/java/com/moa/service/ReplyServiceTest.java
  src/test/java/com/moa/support/fixture/UserFixture.java
Labels: feat

#79 기타 프론트 요구 사항
  src/main/java/com/moa/controller/MainController.java
  src/main/java/com/moa/controller/UserController.java
  src/main/java/com/moa/domain/recruit/RecruitmentRepository.java
  src/main/java/com/moa/domain/user/UserRepository.java
  src/main/java/com/moa/dto/PageCustomResponse.java
  src/main/java/com/moa/dto/SliceResponse.java
  src/main/java/com/moa/global/config/sub/SecurityServiceBeanConfig.java
  src/main/java/com/moa/service/RecruitmentService.java
  src/main/resources/application.yml
Labels: feat

#82 test: 테스트 오류 수정
  src/test/java/com/moa/controller/UserControllerTest.java
  src/test/java/com/moa/service/unit/UserServiceUnitTest.java
Labels: fix, Test

#83 fix: 테스트 에러 수정
  src/main/java/com/moa/domain/recruit/RecruitmentSearchRepository.java
  src/main/java/com/moa/dto/recruit/RecruitmentInfo.java
  src/test/java/com/moa/domain/recruit/RecruitmentSearchRepositoryTest.java
Labels: fix, Test

#86 사용자 관련 링크 기능 추가
  src/main/java/com/moa/controller/LinkController.java
  src/main/java/com/moa/domain/link/Link.java
  src/main/java/com/moa/domain/link/LinkRepository.java
  src/main/java/com/moa/domain/user/User.java
  src/main/java/com/moa/dto/user/UserInfo.java
  src/main/java/com/moa/service/LinkService.java
Labels: feat, Entity

#92 refactor: 참여 시간 로직 수정
  src/main/java/com/moa/InitData.java
  src/main/java/com/moa/controller/PossibleTimeController.java
  src/main/java/com/moa/domain/possible/PossibleTime.java
  src/main/java/com/moa/dto/possible/PossibleTimeData.java
  src/main/java/com/moa/dto/possible/PossibleTimeRequest.java
  src/main/java/com/moa/dto/possible/PossibleTimeResponse.java
  src/main/java/com/moa/service/PossibleTimeService.java
  src/test/java/com/moa/controller/PossibleTimeControllerTest.java
  src/test/java/com/moa/domain/possible/PossibleTimeRepositoryTest.java
  src/test/java/com/moa/dto/possible/PossibleTimeRequestTest.java
  src/test/java/com/moa/dto/possible/PossibleTimeResponseTest.java
  src/test/java/com/moa/service/PossibleTimeServiceTest.java
  src/test/java/com/moa/support/fixture/PossibleTimeFixture.java
Labels: fix, Refactoring

#93 Action: actions 추가
  appspec.yml
  scripts/deploy.sh
Labels: develop, feat

#97 action: action trigger 분리
  .github/workflows/bulid-deploy-PR.yml
  .github/workflows/bulid-deploy-PUSH.yml
Labels: develop, CICD

#100 fix: 모집글 조회 권한 변경
  src/main/java/com/moa/global/config/SecurityConfig.java
Labels: fix

#103 S3 사용자 이미지 업로드
  build.gradle
  src/main/java/com/moa/controller/UserController.java
  src/main/java/com/moa/domain/user/User.java
  src/main/java/com/moa/dto/user/UserInfo.java
  src/main/java/com/moa/global/config/WebBeanConfig.java
  src/main/java/com/moa/global/exception/ErrorCode.java
  src/main/java/com/moa/service/UserService.java
  src/main/java/com/moa/service/util/S3Accessor.java
  src/main/resources/application.yml
  src/main/resources/messages.properties
Labels: feat

#104 프론트 추가 요구사항 해결
  src/main/java/com/moa/domain/member/ApplimentMemberRepository.java
  src/main/java/com/moa/dto/user/UserActivityInfo.java
  src/main/java/com/moa/dto/user/UserInfo.java
  src/main/java/com/moa/dto/user/UserSignupRequest.java
  src/main/java/com/moa/global/config/sub/SecurityFilterBeanConfig.java
  src/main/java/com/moa/global/filter/handler/JwtProviderHandler.java
  src/main/java/com/moa/global/filter/handler/RecruitmentAuthorizationManagerForApplimentMember.java
  src/test/java/com/moa/domain/member/ApplimentMemberRepositoryTest.java
Labels: fix, feat

#105 fix: 오류 수정, 요청/반환 값 변경
  src/main/java/com/moa/domain/member/AdminRepository.java
  src/main/java/com/moa/domain/member/ApplimentMember.java
  src/main/java/com/moa/domain/member/ApplimentMemberRepository.java
  src/main/java/com/moa/domain/member/ApplimentSearchRepository.java
  src/main/java/com/moa/domain/member/RecruitMember.java
  src/main/java/com/moa/domain/recruit/Category.java
  src/main/java/com/moa/domain/recruit/RecruitStatus.java
  src/main/java/com/moa/domain/recruit/Recruitment.java
  src/main/java/com/moa/domain/recruit/RecruitmentSearchRepository.java
  src/main/java/com/moa/dto/member/ApprovedMemberResponse.java
  src/main/java/com/moa/dto/recruit/RecruitInfoResponse.java
  src/main/java/com/moa/dto/recruit/RecruitUpdateRequest.java
  src/main/java/com/moa/dto/recruit/RecruitmentInfo.java
  src/main/java/com/moa/global/exception/ErrorCode.java
  src/main/java/com/moa/global/exception/service/ApplimentStatusChangeException.java
  src/main/java/com/moa/global/exception/service/DuplicateApplyException.java
  src/main/java/com/moa/service/AdminService.java
  src/main/java/com/moa/service/RecruitMemberService.java
  src/main/resources/application.yml
  src/main/resources/messages.properties
  src/test/java/com/moa/controller/AdminControllerTest.java
  src/test/java/com/moa/domain/member/AdminRepositoryTest.java
  src/test/java/com/moa/domain/recruit/RecruitmentSearchRepositoryTest.java
  src/test/java/com/moa/service/AdminServiceTest.java
  src/test/java/com/moa/service/PossibleTimeServiceTest.java
  src/test/java/com/moa/service/unit/RecruitMemberServiceUnitTest.java
  src/test/java/com/moa/support/fixture/RecruitMemberFixture.java
  src/test/java/com/moa/support/fixture/RecruitmentFixture.java
Labels: fix, Refactoring

#111 프론트 요구사항 수정
  src/main/java/com/moa/controller/UserController.java
  src/main/java/com/moa/domain/member/Attendance.java
  src/main/java/com/moa/domain/recruit/Recruitment.java
  src/main/java/com/moa/domain/recruit/tag/RecruitTagRepository.java
  src/main/java/com/moa/domain/user/User.java
  src/main/java/com/moa/dto/notice/NoticesResponse.java
  src/main/java/com/moa/service/RecruitmentService.java
  src/main/java/com/moa/service/UserService.java
  src/test/java/com/moa/controller/NoticeControllerUnitTest.java
  src/test/java/com/moa/service/RecruitmentServiceTest.java
Labels: fix

#114 fix: 시간 저장 리스트 사이즈 1일경우 저장 로직 추가
  src/main/java/com/moa/dto/possible/PossibleTimeRequest.java
  src/main/java/com/moa/dto/recruit/RecruitInfoResponse.java
  src/main/java/com/moa/dto/user/UserIdNameNicknameResponse.java
Labels: fix

#121 feat: 레벨별 로그 파일 저장
  log/error/error-2023-04-27.log
  log/info/info-2023-04-27.log
  log/warn/warn-2023-04-27.log
  src/main/java/com/moa/global/filter/BusinessExceptionHandlerFilter.java
  src/main/resources/log/console-appender.xml
  src/main/resources/log/file-error-appender.xml
  src/main/resources/log/file-info-appender.xml
  src/main/resources/log/file-warn-appender.xml
  src/main/resources/logback-spring.xml
Labels: develop

#124 fix: 인기도 버그 수정
  src/main/java/com/moa/domain/user/Popularity.java
  src/main/java/com/moa/global/config/WebBeanConfig.java
  src/main/java/com/moa/logging/LoggingFilter.java
  src/test/java/com/moa/service/AdminServiceTest.java
  src/test/java/com/moa/support/fixture/ApplimentFixture.java
  src/test/java/com/moa/support/fixture/RecruitmentFixture.java
Labels: fix
